// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/authorization/adapter.go
//
// Generated by this command:
//
//	mockgen -package=authorization -destination=pkg/authorization/adapter_mock.go -source=pkg/authorization/adapter.go OrganizationRepository
//

// Package authorization is a generated GoMock package.
package authorization

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationRepository is a mock of OrganizationRepository interface.
type MockOrganizationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationRepositoryMockRecorder
	isgomock struct{}
}

// MockOrganizationRepositoryMockRecorder is the mock recorder for MockOrganizationRepository.
type MockOrganizationRepositoryMockRecorder struct {
	mock *MockOrganizationRepository
}

// NewMockOrganizationRepository creates a new mock instance.
func NewMockOrganizationRepository(ctrl *gomock.Controller) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationRepository) EXPECT() *MockOrganizationRepositoryMockRecorder {
	return m.recorder
}

// GetMemberRoleString mocks base method.
func (m *MockOrganizationRepository) GetMemberRoleString(ctx context.Context, organizationId, userId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRoleString", ctx, organizationId, userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRoleString indicates an expected call of GetMemberRoleString.
func (mr *MockOrganizationRepositoryMockRecorder) GetMemberRoleString(ctx, organizationId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRoleString", reflect.TypeOf((*MockOrganizationRepository)(nil).GetMemberRoleString), ctx, organizationId, userId)
}
