// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/idempotency/interceptor.go
//
// Generated by this command:
//
//	mockgen -package=idempotency -destination=pkg/idempotency/interceptor_mock.go -source=pkg/idempotency/interceptor.go IdempotencyRepository
//

// Package idempotency is a generated GoMock package.
package idempotency

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdempotencyRepository is a mock of IdempotencyRepository interface.
type MockIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyRepositoryMockRecorder
	isgomock struct{}
}

// MockIdempotencyRepositoryMockRecorder is the mock recorder for MockIdempotencyRepository.
type MockIdempotencyRepositoryMockRecorder struct {
	mock *MockIdempotencyRepository
}

// NewMockIdempotencyRepository creates a new mock instance.
func NewMockIdempotencyRepository(ctrl *gomock.Controller) *MockIdempotencyRepository {
	mock := &MockIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockIdempotencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyRepository) EXPECT() *MockIdempotencyRepositoryMockRecorder {
	return m.recorder
}

// ClaimIdempotencyKey mocks base method.
func (m *MockIdempotencyRepository) ClaimIdempotencyKey(ctx context.Context, key, operation, requestHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimIdempotencyKey", ctx, key, operation, requestHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClaimIdempotencyKey indicates an expected call of ClaimIdempotencyKey.
func (mr *MockIdempotencyRepositoryMockRecorder) ClaimIdempotencyKey(ctx, key, operation, requestHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimIdempotencyKey", reflect.TypeOf((*MockIdempotencyRepository)(nil).ClaimIdempotencyKey), ctx, key, operation, requestHash)
}

// EndOperation mocks base method.
func (m *MockIdempotencyRepository) EndOperation(ctx context.Context, key, response, err string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndOperation", ctx, key, response, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndOperation indicates an expected call of EndOperation.
func (mr *MockIdempotencyRepositoryMockRecorder) EndOperation(ctx, key, response, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndOperation", reflect.TypeOf((*MockIdempotencyRepository)(nil).EndOperation), ctx, key, response, err)
}

// IsIdempotencyKeyExists mocks base method.
func (m *MockIdempotencyRepository) IsIdempotencyKeyExists(ctx context.Context, key string) (error, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsIdempotencyKeyExists", ctx, key)
	ret0, _ := ret[0].(error)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// IsIdempotencyKeyExists indicates an expected call of IsIdempotencyKeyExists.
func (mr *MockIdempotencyRepositoryMockRecorder) IsIdempotencyKeyExists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsIdempotencyKeyExists", reflect.TypeOf((*MockIdempotencyRepository)(nil).IsIdempotencyKeyExists), ctx, key)
}
