# path: apps/api/go.mod
# The original go.mod dropped the BSR import in favor of the local
# generated protobuf output from the monorepo root. See ADR-0004.
module hasir-api

go 1.26

require (
	connectrpc.com/connect v1.20.0
	github.com/exaring/otelpgx v0.11.1
	github.com/gliderlabs/ssh v0.3.8
	github.com/go-git/go-git/v5 v5.19.1
	github.com/golang-jwt/jwt/v5 v5.3.1
	github.com/golang-migrate/migrate/v4 v4.19.1
	github.com/google/uuid v1.6.0
	github.com/jackc/pgx/v5 v5.10.0
	github.com/knadh/koanf/parsers/json v1.0.0
	github.com/knadh/koanf/providers/env v1.1.0
	github.com/knadh/koanf/providers/file v1.2.1
	github.com/knadh/koanf/v2 v2.3.5
	github.com/rs/cors v1.11.1
	github.com/stretchr/testify v1.11.1
	github.com/testcontainers/testcontainers-go/modules/postgres v0.42.0
	go.opentelemetry.io/otel v1.44.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.44.0
	go.opentelemetry.io/otel/sdk v1.44.0
	go.opentelemetry.io/otel/trace v1.44.0
	go.uber.org/mock v0.6.0
	go.uber.org/zap v1.28.0
	golang.org/x/crypto v0.54.0
	golang.org/x/sync v0.22.0
	google.golang.org/protobuf v1.36.11
    
	# Local module (from proto/gen/go generated by `turbo proto`)
	github.com/protohasir/hasir/proto/gen/go v0.0.0-00010101000000-000000000000
)

replace github.com/protohasir/hasir/proto/gen/go => ../../proto/gen/go
